CREATE TABLE IF NOT EXISTS archive_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    year_label VARCHAR(40) NOT NULL,
    title VARCHAR(255) NOT NULL,
    doc_type VARCHAR(120) NOT NULL,
    link_url VARCHAR(1000) NULL,
    file_path VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_archive_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
